// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: INodeRunnerRemote.proto

package ins.daemon.node;

public interface checkDeamonStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ins.daemon.node.checkDeamonStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool message = 1;</code>
   * @return The message.
   */
  boolean getMessage();
}
