// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: INodeRunnerRemote.proto

package ins.daemon.node;

public final class INodeRunnerRt {
  private INodeRunnerRt() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ins_daemon_node_restartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ins_daemon_node_restartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ins_daemon_node_restartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ins_daemon_node_restartResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ins_daemon_node_firmwareRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ins_daemon_node_firmwareRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ins_daemon_node_firmwareResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ins_daemon_node_firmwareResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ins_daemon_node_ResEntity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ins_daemon_node_ResEntity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ins_daemon_node_checkDeamonStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ins_daemon_node_checkDeamonStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ins_daemon_node_resetDeviceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ins_daemon_node_resetDeviceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ins_daemon_node_SysInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ins_daemon_node_SysInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ins_daemon_node_SysInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ins_daemon_node_SysInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ins_daemon_node_lsEndModuleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ins_daemon_node_lsEndModuleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ins_daemon_node_updateDSPRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ins_daemon_node_updateDSPRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ins_daemon_node_updateAppRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ins_daemon_node_updateAppRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ins_daemon_node_updateAppResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ins_daemon_node_updateAppResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ins_daemon_node_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ins_daemon_node_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ins_daemon_node_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ins_daemon_node_HelloResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ins_daemon_node_HellosRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ins_daemon_node_HellosRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ins_daemon_node_HellosResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ins_daemon_node_HellosResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ins_daemon_node_PrintLogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ins_daemon_node_PrintLogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ins_daemon_node_RunAppResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ins_daemon_node_RunAppResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ins_daemon_node_StatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ins_daemon_node_StatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027INodeRunnerRemote.proto\022\017ins.daemon.no" +
      "de\032\033google/protobuf/empty.proto\"\035\n\016resta" +
      "rtRequest\022\013\n\003num\030\001 \001(\t\"\"\n\017restartRespons" +
      "e\022\017\n\007message\030\001 \001(\005\":\n\017firmwareRequest\022\014\n" +
      "\004name\030\001 \001(\t\022\014\n\004data\030\002 \001(\014\022\013\n\003num\030\003 \001(\t\"#" +
      "\n\020firmwareResponse\022\017\n\007message\030\001 \001(\005\"\210\001\n\t" +
      "ResEntity\022\014\n\004name\030\001 \001(\t\022\014\n\004type\030\002 \001(\t\022\013\n" +
      "\003tag\030\003 \001(\t\022\016\n\006length\030\004 \001(\t\022\013\n\003def\030\005 \001(\t\022" +
      "\017\n\007options\030\006 \001(\t\022\020\n\010dataType\030\007 \001(\t\022\022\n\npa" +
      "rentName\030\010 \001(\t\",\n\031checkDeamonStatusRespo" +
      "nse\022\017\n\007message\030\001 \001(\010\"&\n\023resetDeviceRespo" +
      "nse\022\017\n\007message\030\001 \001(\005\"\035\n\016SysInfoRequest\022\013" +
      "\n\003str\030\001 \001(\t\"\"\n\017SysInfoResponse\022\017\n\007messag" +
      "e\030\001 \001(\t\"&\n\023lsEndModuleResponse\022\017\n\007messag" +
      "e\030\001 \001(\t\"2\n\020updateDSPRequest\022\020\n\010resource\030" +
      "\001 \001(\t\022\014\n\004data\030\002 \003(\014\">\n\020updateAppRequest\022" +
      "\014\n\004name\030\001 \001(\t\022\r\n\005files\030\002 \001(\014\022\r\n\005force\030\003 " +
      "\001(\010\"$\n\021updateAppResponse\022\017\n\007message\030\001 \001(" +
      "\005\"\034\n\014HelloRequest\022\014\n\004name\030\001 \001(\t\" \n\rHello" +
      "Response\022\017\n\007message\030\001 \001(\t\"\035\n\rHellosReque" +
      "st\022\014\n\004name\030\001 \001(\t\"!\n\016HellosResponse\022\017\n\007me" +
      "ssage\030\001 \001(\t\"\"\n\017PrintLogRequest\022\017\n\007logNam" +
      "e\030\001 \001(\t\"!\n\016RunAppResponse\022\017\n\007message\030\001 \001" +
      "(\t\"!\n\016StatusResponse\022\017\n\007message\030\001 \001(\0102\235\t" +
      "\n\021INodeRunnerRemote\022K\n\010sayHello\022\035.ins.da" +
      "emon.node.HelloRequest\032\036.ins.daemon.node" +
      ".HelloResponse\"\000\022O\n\nhelloWorld\022\036.ins.dae" +
      "mon.node.HellosRequest\032\037.ins.daemon.node" +
      ".HellosResponse\"\000\022D\n\006runApp\022 .ins.daemon" +
      ".node.PrintLogRequest\032\026.google.protobuf." +
      "Empty\"\000\022;\n\007killApp\022\026.google.protobuf.Emp" +
      "ty\032\026.google.protobuf.Empty\"\000\022K\n\016checkApp" +
      "Status\022\026.google.protobuf.Empty\032\037.ins.dae" +
      "mon.node.StatusResponse\"\000\022Y\n\021checkDeamon" +
      "Status\022\026.google.protobuf.Empty\032*.ins.dae" +
      "mon.node.checkDeamonStatusResponse\"\000\022V\n\t" +
      "updateApp\022!.ins.daemon.node.updateAppReq" +
      "uest\032\".ins.daemon.node.updateAppResponse" +
      "\"\000(\001\022H\n\tupdateDSP\022!.ins.daemon.node.upda" +
      "teDSPRequest\032\026.google.protobuf.Empty\"\000\022M" +
      "\n\013lsEndModule\022\026.google.protobuf.Empty\032$." +
      "ins.daemon.node.lsEndModuleResponse\"\000\022Q\n" +
      "\ngetSysInfo\022\037.ins.daemon.node.SysInfoReq" +
      "uest\032 .ins.daemon.node.SysInfoResponse\"\000" +
      "\022?\n\013fakeSendMsg\022\026.google.protobuf.Empty\032" +
      "\026.google.protobuf.Empty\"\000\022M\n\013resetDevice" +
      "\022\026.google.protobuf.Empty\032$.ins.daemon.no" +
      "de.resetDeviceResponse\"\000\022@\n\010setParam\022\032.i" +
      "ns.daemon.node.ResEntity\032\026.google.protob" +
      "uf.Empty\"\000\022Y\n\016updateFirmware\022 .ins.daemo" +
      "n.node.firmwareRequest\032!.ins.daemon.node" +
      ".firmwareResponse\"\000(\001\022N\n\007restart\022\037.ins.d" +
      "aemon.node.restartRequest\032 .ins.daemon.n" +
      "ode.restartResponse\"\000B+\n\017ins.daemon.node" +
      "B\rINodeRunnerRtP\001\242\002\006daemonb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_ins_daemon_node_restartRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ins_daemon_node_restartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ins_daemon_node_restartRequest_descriptor,
        new String[] { "Num", });
    internal_static_ins_daemon_node_restartResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ins_daemon_node_restartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ins_daemon_node_restartResponse_descriptor,
        new String[] { "Message", });
    internal_static_ins_daemon_node_firmwareRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ins_daemon_node_firmwareRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ins_daemon_node_firmwareRequest_descriptor,
        new String[] { "Name", "Data", "Num", });
    internal_static_ins_daemon_node_firmwareResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ins_daemon_node_firmwareResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ins_daemon_node_firmwareResponse_descriptor,
        new String[] { "Message", });
    internal_static_ins_daemon_node_ResEntity_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ins_daemon_node_ResEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ins_daemon_node_ResEntity_descriptor,
        new String[] { "Name", "Type", "Tag", "Length", "Def", "Options", "DataType", "ParentName", });
    internal_static_ins_daemon_node_checkDeamonStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ins_daemon_node_checkDeamonStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ins_daemon_node_checkDeamonStatusResponse_descriptor,
        new String[] { "Message", });
    internal_static_ins_daemon_node_resetDeviceResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ins_daemon_node_resetDeviceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ins_daemon_node_resetDeviceResponse_descriptor,
        new String[] { "Message", });
    internal_static_ins_daemon_node_SysInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ins_daemon_node_SysInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ins_daemon_node_SysInfoRequest_descriptor,
        new String[] { "Str", });
    internal_static_ins_daemon_node_SysInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_ins_daemon_node_SysInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ins_daemon_node_SysInfoResponse_descriptor,
        new String[] { "Message", });
    internal_static_ins_daemon_node_lsEndModuleResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_ins_daemon_node_lsEndModuleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ins_daemon_node_lsEndModuleResponse_descriptor,
        new String[] { "Message", });
    internal_static_ins_daemon_node_updateDSPRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_ins_daemon_node_updateDSPRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ins_daemon_node_updateDSPRequest_descriptor,
        new String[] { "Resource", "Data", });
    internal_static_ins_daemon_node_updateAppRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_ins_daemon_node_updateAppRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ins_daemon_node_updateAppRequest_descriptor,
        new String[] { "Name", "Files", "Force", });
    internal_static_ins_daemon_node_updateAppResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_ins_daemon_node_updateAppResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ins_daemon_node_updateAppResponse_descriptor,
        new String[] { "Message", });
    internal_static_ins_daemon_node_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_ins_daemon_node_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ins_daemon_node_HelloRequest_descriptor,
        new String[] { "Name", });
    internal_static_ins_daemon_node_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_ins_daemon_node_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ins_daemon_node_HelloResponse_descriptor,
        new String[] { "Message", });
    internal_static_ins_daemon_node_HellosRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_ins_daemon_node_HellosRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ins_daemon_node_HellosRequest_descriptor,
        new String[] { "Name", });
    internal_static_ins_daemon_node_HellosResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_ins_daemon_node_HellosResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ins_daemon_node_HellosResponse_descriptor,
        new String[] { "Message", });
    internal_static_ins_daemon_node_PrintLogRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_ins_daemon_node_PrintLogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ins_daemon_node_PrintLogRequest_descriptor,
        new String[] { "LogName", });
    internal_static_ins_daemon_node_RunAppResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_ins_daemon_node_RunAppResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ins_daemon_node_RunAppResponse_descriptor,
        new String[] { "Message", });
    internal_static_ins_daemon_node_StatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_ins_daemon_node_StatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ins_daemon_node_StatusResponse_descriptor,
        new String[] { "Message", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
