// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: INodeRunnerRemote.proto

package ins.daemon.node;

public interface ResEntityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ins.daemon.node.ResEntity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string type = 2;</code>
   * @return The type.
   */
  String getType();
  /**
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string tag = 3;</code>
   * @return The tag.
   */
  String getTag();
  /**
   * <code>string tag = 3;</code>
   * @return The bytes for tag.
   */
  com.google.protobuf.ByteString
      getTagBytes();

  /**
   * <code>string length = 4;</code>
   * @return The length.
   */
  String getLength();
  /**
   * <code>string length = 4;</code>
   * @return The bytes for length.
   */
  com.google.protobuf.ByteString
      getLengthBytes();

  /**
   * <code>string def = 5;</code>
   * @return The def.
   */
  String getDef();
  /**
   * <code>string def = 5;</code>
   * @return The bytes for def.
   */
  com.google.protobuf.ByteString
      getDefBytes();

  /**
   * <code>string options = 6;</code>
   * @return The options.
   */
  String getOptions();
  /**
   * <code>string options = 6;</code>
   * @return The bytes for options.
   */
  com.google.protobuf.ByteString
      getOptionsBytes();

  /**
   * <code>string dataType = 7;</code>
   * @return The dataType.
   */
  String getDataType();
  /**
   * <code>string dataType = 7;</code>
   * @return The bytes for dataType.
   */
  com.google.protobuf.ByteString
      getDataTypeBytes();

  /**
   * <code>string parentName = 8;</code>
   * @return The parentName.
   */
  String getParentName();
  /**
   * <code>string parentName = 8;</code>
   * @return The bytes for parentName.
   */
  com.google.protobuf.ByteString
      getParentNameBytes();
}
