// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: INodeRunnerRemote.proto

package ins.daemon.node;

/**
 * Protobuf type {@code ins.daemon.node.ResEntity}
 */
public final class ResEntity extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ins.daemon.node.ResEntity)
    ResEntityOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResEntity.newBuilder() to construct.
  private ResEntity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResEntity() {
    name_ = "";
    type_ = "";
    tag_ = "";
    length_ = "";
    def_ = "";
    options_ = "";
    dataType_ = "";
    parentName_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResEntity();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return INodeRunnerRt.internal_static_ins_daemon_node_ResEntity_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return INodeRunnerRt.internal_static_ins_daemon_node_ResEntity_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ResEntity.class, Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object name_ = "";
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @Override
  public String getName() {
    Object ref = name_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    Object ref = name_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object type_ = "";
  /**
   * <code>string type = 2;</code>
   * @return The type.
   */
  @Override
  public String getType() {
    Object ref = type_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  @Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    Object ref = type_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TAG_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile Object tag_ = "";
  /**
   * <code>string tag = 3;</code>
   * @return The tag.
   */
  @Override
  public String getTag() {
    Object ref = tag_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      tag_ = s;
      return s;
    }
  }
  /**
   * <code>string tag = 3;</code>
   * @return The bytes for tag.
   */
  @Override
  public com.google.protobuf.ByteString
      getTagBytes() {
    Object ref = tag_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      tag_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LENGTH_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile Object length_ = "";
  /**
   * <code>string length = 4;</code>
   * @return The length.
   */
  @Override
  public String getLength() {
    Object ref = length_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      length_ = s;
      return s;
    }
  }
  /**
   * <code>string length = 4;</code>
   * @return The bytes for length.
   */
  @Override
  public com.google.protobuf.ByteString
      getLengthBytes() {
    Object ref = length_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      length_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEF_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile Object def_ = "";
  /**
   * <code>string def = 5;</code>
   * @return The def.
   */
  @Override
  public String getDef() {
    Object ref = def_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      def_ = s;
      return s;
    }
  }
  /**
   * <code>string def = 5;</code>
   * @return The bytes for def.
   */
  @Override
  public com.google.protobuf.ByteString
      getDefBytes() {
    Object ref = def_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      def_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPTIONS_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile Object options_ = "";
  /**
   * <code>string options = 6;</code>
   * @return The options.
   */
  @Override
  public String getOptions() {
    Object ref = options_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      options_ = s;
      return s;
    }
  }
  /**
   * <code>string options = 6;</code>
   * @return The bytes for options.
   */
  @Override
  public com.google.protobuf.ByteString
      getOptionsBytes() {
    Object ref = options_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      options_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATATYPE_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile Object dataType_ = "";
  /**
   * <code>string dataType = 7;</code>
   * @return The dataType.
   */
  @Override
  public String getDataType() {
    Object ref = dataType_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      dataType_ = s;
      return s;
    }
  }
  /**
   * <code>string dataType = 7;</code>
   * @return The bytes for dataType.
   */
  @Override
  public com.google.protobuf.ByteString
      getDataTypeBytes() {
    Object ref = dataType_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      dataType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARENTNAME_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile Object parentName_ = "";
  /**
   * <code>string parentName = 8;</code>
   * @return The parentName.
   */
  @Override
  public String getParentName() {
    Object ref = parentName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      parentName_ = s;
      return s;
    }
  }
  /**
   * <code>string parentName = 8;</code>
   * @return The bytes for parentName.
   */
  @Override
  public com.google.protobuf.ByteString
      getParentNameBytes() {
    Object ref = parentName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      parentName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tag_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, tag_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(length_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, length_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(def_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, def_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(options_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, options_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dataType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, dataType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parentName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, parentName_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tag_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, tag_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(length_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, length_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(def_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, def_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(options_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, options_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dataType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, dataType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parentName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, parentName_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ResEntity)) {
      return super.equals(obj);
    }
    ResEntity other = (ResEntity) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getType()
        .equals(other.getType())) return false;
    if (!getTag()
        .equals(other.getTag())) return false;
    if (!getLength()
        .equals(other.getLength())) return false;
    if (!getDef()
        .equals(other.getDef())) return false;
    if (!getOptions()
        .equals(other.getOptions())) return false;
    if (!getDataType()
        .equals(other.getDataType())) return false;
    if (!getParentName()
        .equals(other.getParentName())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + TAG_FIELD_NUMBER;
    hash = (53 * hash) + getTag().hashCode();
    hash = (37 * hash) + LENGTH_FIELD_NUMBER;
    hash = (53 * hash) + getLength().hashCode();
    hash = (37 * hash) + DEF_FIELD_NUMBER;
    hash = (53 * hash) + getDef().hashCode();
    hash = (37 * hash) + OPTIONS_FIELD_NUMBER;
    hash = (53 * hash) + getOptions().hashCode();
    hash = (37 * hash) + DATATYPE_FIELD_NUMBER;
    hash = (53 * hash) + getDataType().hashCode();
    hash = (37 * hash) + PARENTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getParentName().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ResEntity parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ResEntity parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ResEntity parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ResEntity parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ResEntity parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ResEntity parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ResEntity parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ResEntity parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ResEntity parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ResEntity parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ResEntity parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ResEntity parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ResEntity prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ins.daemon.node.ResEntity}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ins.daemon.node.ResEntity)
      ResEntityOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return INodeRunnerRt.internal_static_ins_daemon_node_ResEntity_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return INodeRunnerRt.internal_static_ins_daemon_node_ResEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ResEntity.class, Builder.class);
    }

    // Construct using ins.daemon.node.ResEntity.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      type_ = "";
      tag_ = "";
      length_ = "";
      def_ = "";
      options_ = "";
      dataType_ = "";
      parentName_ = "";
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return INodeRunnerRt.internal_static_ins_daemon_node_ResEntity_descriptor;
    }

    @Override
    public ResEntity getDefaultInstanceForType() {
      return ResEntity.getDefaultInstance();
    }

    @Override
    public ResEntity build() {
      ResEntity result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ResEntity buildPartial() {
      ResEntity result = new ResEntity(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ResEntity result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.tag_ = tag_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.length_ = length_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.def_ = def_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.options_ = options_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.dataType_ = dataType_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.parentName_ = parentName_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ResEntity) {
        return mergeFrom((ResEntity)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ResEntity other) {
      if (other == ResEntity.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getTag().isEmpty()) {
        tag_ = other.tag_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getLength().isEmpty()) {
        length_ = other.length_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getDef().isEmpty()) {
        def_ = other.def_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getOptions().isEmpty()) {
        options_ = other.options_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getDataType().isEmpty()) {
        dataType_ = other.dataType_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getParentName().isEmpty()) {
        parentName_ = other.parentName_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              type_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              tag_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              length_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              def_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              options_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              dataType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              parentName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public String getName() {
      Object ref = name_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private Object type_ = "";
    /**
     * <code>string type = 2;</code>
     * @return The type.
     */
    public String getType() {
      Object ref = type_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string type = 2;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type = 2;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      type_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      type_ = getDefaultInstance().getType();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string type = 2;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      type_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private Object tag_ = "";
    /**
     * <code>string tag = 3;</code>
     * @return The tag.
     */
    public String getTag() {
      Object ref = tag_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tag_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string tag = 3;</code>
     * @return The bytes for tag.
     */
    public com.google.protobuf.ByteString
        getTagBytes() {
      Object ref = tag_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tag = 3;</code>
     * @param value The tag to set.
     * @return This builder for chaining.
     */
    public Builder setTag(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      tag_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string tag = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTag() {
      tag_ = getDefaultInstance().getTag();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string tag = 3;</code>
     * @param value The bytes for tag to set.
     * @return This builder for chaining.
     */
    public Builder setTagBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tag_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private Object length_ = "";
    /**
     * <code>string length = 4;</code>
     * @return The length.
     */
    public String getLength() {
      Object ref = length_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        length_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string length = 4;</code>
     * @return The bytes for length.
     */
    public com.google.protobuf.ByteString
        getLengthBytes() {
      Object ref = length_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        length_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string length = 4;</code>
     * @param value The length to set.
     * @return This builder for chaining.
     */
    public Builder setLength(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      length_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string length = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLength() {
      length_ = getDefaultInstance().getLength();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string length = 4;</code>
     * @param value The bytes for length to set.
     * @return This builder for chaining.
     */
    public Builder setLengthBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      length_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private Object def_ = "";
    /**
     * <code>string def = 5;</code>
     * @return The def.
     */
    public String getDef() {
      Object ref = def_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        def_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string def = 5;</code>
     * @return The bytes for def.
     */
    public com.google.protobuf.ByteString
        getDefBytes() {
      Object ref = def_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        def_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string def = 5;</code>
     * @param value The def to set.
     * @return This builder for chaining.
     */
    public Builder setDef(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      def_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string def = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDef() {
      def_ = getDefaultInstance().getDef();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string def = 5;</code>
     * @param value The bytes for def to set.
     * @return This builder for chaining.
     */
    public Builder setDefBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      def_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private Object options_ = "";
    /**
     * <code>string options = 6;</code>
     * @return The options.
     */
    public String getOptions() {
      Object ref = options_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        options_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string options = 6;</code>
     * @return The bytes for options.
     */
    public com.google.protobuf.ByteString
        getOptionsBytes() {
      Object ref = options_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        options_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string options = 6;</code>
     * @param value The options to set.
     * @return This builder for chaining.
     */
    public Builder setOptions(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      options_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string options = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearOptions() {
      options_ = getDefaultInstance().getOptions();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string options = 6;</code>
     * @param value The bytes for options to set.
     * @return This builder for chaining.
     */
    public Builder setOptionsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      options_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private Object dataType_ = "";
    /**
     * <code>string dataType = 7;</code>
     * @return The dataType.
     */
    public String getDataType() {
      Object ref = dataType_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dataType_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string dataType = 7;</code>
     * @return The bytes for dataType.
     */
    public com.google.protobuf.ByteString
        getDataTypeBytes() {
      Object ref = dataType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dataType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dataType = 7;</code>
     * @param value The dataType to set.
     * @return This builder for chaining.
     */
    public Builder setDataType(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      dataType_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string dataType = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearDataType() {
      dataType_ = getDefaultInstance().getDataType();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string dataType = 7;</code>
     * @param value The bytes for dataType to set.
     * @return This builder for chaining.
     */
    public Builder setDataTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      dataType_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private Object parentName_ = "";
    /**
     * <code>string parentName = 8;</code>
     * @return The parentName.
     */
    public String getParentName() {
      Object ref = parentName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        parentName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string parentName = 8;</code>
     * @return The bytes for parentName.
     */
    public com.google.protobuf.ByteString
        getParentNameBytes() {
      Object ref = parentName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        parentName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string parentName = 8;</code>
     * @param value The parentName to set.
     * @return This builder for chaining.
     */
    public Builder setParentName(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      parentName_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string parentName = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearParentName() {
      parentName_ = getDefaultInstance().getParentName();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string parentName = 8;</code>
     * @param value The bytes for parentName to set.
     * @return This builder for chaining.
     */
    public Builder setParentNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      parentName_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ins.daemon.node.ResEntity)
  }

  // @@protoc_insertion_point(class_scope:ins.daemon.node.ResEntity)
  private static final ResEntity DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ResEntity();
  }

  public static ResEntity getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResEntity>
      PARSER = new com.google.protobuf.AbstractParser<ResEntity>() {
    @Override
    public ResEntity parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ResEntity> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ResEntity> getParserForType() {
    return PARSER;
  }

  @Override
  public ResEntity getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

