// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: INodeRunnerRemote.proto

package ins.daemon.node;

public interface resetDeviceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ins.daemon.node.resetDeviceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 message = 1;</code>
   * @return The message.
   */
  int getMessage();
}
