// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: INodeRunnerRemote.proto

package ins.daemon.node;

public interface restartRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ins.daemon.node.restartRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string num = 1;</code>
   * @return The num.
   */
  String getNum();
  /**
   * <code>string num = 1;</code>
   * @return The bytes for num.
   */
  com.google.protobuf.ByteString
      getNumBytes();
}
