// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: INodeRunnerRemote.proto

package ins.daemon.node;

public interface SysInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ins.daemon.node.SysInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string str = 1;</code>
   * @return The str.
   */
  String getStr();
  /**
   * <code>string str = 1;</code>
   * @return The bytes for str.
   */
  com.google.protobuf.ByteString
      getStrBytes();
}
